export const CLASSES = {
    1: 'rice',
    2: 'eels on rice',
    3: 'fried rice',
    4: 'pork cutlet on rice',
    5: 'sushi',
    6: 'bibimbap',
    7: 'toast',
    8: 'croissant',
    9: 'hamburger',
    10: 'pizza',
    11: 'sandwiches',
    12: 'spaghetti',
    13: 'takoyaki',
    14: 'gratin',
    15: 'miso soup',
    16: 'potage',
    17: 'sashimi',
    18: 'grilled pacific saury',
    19: 'tempura',
    20: 'sirloin cutlet',
    21: 'hambarg steak, hamburger_steak',
    22: 'beef steak',
    23: 'spicy chili-flavored tofu',
    24: 'yakitori',
    25: 'rolled omelet',
    26: 'egg sunny-side up',
    27: 'cold tofu',
    28: 'chicken',
    29: 'sushi bowl',
    30: 'fish-shaped pancake with bean jam',
    31: 'shrimp with chill source',
    32: 'steamed meat dumpling',
    33: 'egg_rice',
    34: 'cutlet curry',
    35: 'fried shrimp',
    36: 'green salad',
    37: 'beef bowl',
    38: 'hot dog',
    39: 'french fries',
    40: 'ramen',
    41: 'steamedegg',
    42: 'vegetable pancake',
    43: 'kimchi',
    44: 'kimchi stew',
    45: 'bossam',
    46: 'kimbap',
    47: 'grilled pork belly',
    48: 'black bean sauce noodles',
    49: 'sausage stew',
    50: 'tteokbokki',
    51: 'pork tripe',
    52: 'samgyetang',
    53: 'doenjang',
    54: 'gamjatang',
    55: 'jjamppong',
    56: 'sundae',
    57: 'kalguksu',
    58: 'tteokguk',
    59: 'bulgogi',
    60: 'japchae',
    61: 'naengmyeon',
    62: 'small octopus',
    63: 'ice_flakes'
};